package com.model;
// Generated 25-Aug-2019 13:24:18 by Hibernate Tools 4.3.1



/**
 * Parvez generated by hbm2java
 */
public class Parvez  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String self;
     private String date;
     private Integer qty;
     private Float price;

    public Parvez() {
    }

    public Parvez(String name, String self, String date, Integer qty, Float price) {
       this.name = name;
       this.self = self;
       this.date = date;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSelf() {
        return this.self;
    }
    
    public void setSelf(String self) {
        this.self = self;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }




}


